version: '2'
services:
  altkomdevelopers-app:
    image: altkomdevelopers
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://altkomdevelopers-mariadb:3306/altkomdevelopers
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  altkomdevelopers-mariadb:
    extends:
      file: mariadb.yml
      service: altkomdevelopers-mariadb
